
services:
  db:
    image: postgres:16
    container_name: mydb
    environment:
      POSTGRES_DB: task_db
      POSTGRES_USER: ${DB_LOGIN}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d mydb" ]
      interval: 5s
      timeout: 5s
      retries: 10

    ports:
      - "5432:5432"

#  frontend:
#    build:
#      context: ./frontend
#      args:
#        NGINX_ENV: .dev
#    ports:
#      - "80:80"

  app:
    container_name: task-app
    build: .
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    expose:
      - "8080"

  redis:
    container_name: redis
    image: redis:8
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
  redis-data:
