
services:

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html

  acme-companion:
    image: nginxproxy/acme-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro



  db:
    image: postgres:16
    container_name: mydb
    environment:
      POSTGRES_DB: task_db
      POSTGRES_USER: ${DB_LOGIN}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U arturka -d mydb" ]
      interval: 5s
      timeout: 5s
      retries: 10

    ports:
      - "5432:5432"

  kafka:
    image: bitnamilegacy/kafka:3.9
    ports:
      - "9092"
    env_file:
      - .env.kafka
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1 || exit 1"
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s



  frontend:
    container_name: task-frontend
    image: appleapplenotdead/task-tracker-frontend:latest
    expose:
      - "80"
    environment:
      VIRTUAL_HOST: task-tracker.codeportfolio.ru
      LETSENCRYPT_HOST: task-tracker.codeportfolio.ru
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

  task-app:
    container_name: task-app
    image: appleapplenotdead/task-tracker-backend:latest
    env_file:
      - .env.backend # JWT + password for user
      - .env # DB
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  email-sender:
    container_name: email-sender
    image: appleapplenotdead/task-tracker-email-sender:latest
    env_file:
      - .env.email
    expose:
      - "8090"


  scheduler:
    container_name: scheduler
    image: appleapplenotdead/task-tracker-scheduler:latest
    env_file:
      - .env
    expose:
      - "8091"


  summarizer:
    container_name: summarizer
    image: appleapplenotdead/task-tracker-summarizer:latest
    env_file:
      - .env.ai
    expose:
      - "8092"


  simulation:
    container_name: simulation
    image: ghcr.io/rocknrollnotdead/simulation:latest
    expose:
      - "8085"
    environment:
      PORT: 8085
      VIRTUAL_HOST: simulation-project.codeportfolio.ru
      VIRTUAL_PORT: 8085
      LETSENCRYPT_HOST: simulation-project.codeportfolio.ru
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    env_file:
      - .env.simulation

  tomcat-app:
    image: ghcr.io/rocknrollnotdead/tomcat-app:latest
    env_file:
      - .env
    environment:
      DB_URL: db:5432/tennis_scoreboard

      DB_PATH: /var/lib/currency-exchange/database.db

      VIRTUAL_HOST: codeportfolio.ru
      VIRTUAL_PORT: 8080
      VIRTUAL_PATH: /
      LETSENCRYPT_HOST: codeportfolio.ru
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

    expose:
      - "8080"
    volumes:
      - sqlite-data:/var/lib/currency-exchange




  app-cloud:
    image: ghcr.io/rocknrollnotdead/cloud-file-storage:latest
    env_file:
      - .env.cloud
      - .env
    depends_on:
      mydb:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8080/ || exit 1"]
      start_period: 40s

  frontend-cloud:
    image: ghcr.io/rocknrollnotdead/cloud-storage-frontend:latest
    environment:
      VIRTUAL_HOST: cloud-file-storage.codeportfolio.ru
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: cloud-file-storage.codeportfolio.ru
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

    expose:
      - "80"



  redis:
    container_name: redis
    image: redis:8
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10

  minio:
    # Используемый образ Docker. Рекомендуется указывать конкретный тег для стабильности.
    image: minio/minio:RELEASE.2024-04-18T19-09-19Z
    container_name: s3
    command: server /data --address ":9010" --console-address ":9011"
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: ${PASSWORD}

    expose:
      - "9010"
      - "9011"
    volumes:
      - minio-data:/data
    deploy:
      resources:
        limits:
          memory: 1024m
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    healthcheck:
      test:  [ "CMD-SHELL", "curl -f http://localhost:9010/minio/health/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s


volumes:
  pgdata:
  sqlite-data:
  redis-data:
  minio-data:

  certs:
  vhost:
  html:
  acme:



