spring:
  datasource:
    username: ${DB_LOGIN:postgres}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false

secret-key: ${SECRET_KEY_JWT:7f3a9c8e1b4d6f2a5e8c9d0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f}

secrets:
  user:
    password: ${PASSWORD_USER:password123}
    username: User
  admin:
    password: ${DB_PASSWORD:admin123}
    username: ${DB_LOGIN:admin}